// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcserver.proto

package protomsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MsgFromMsgServerRequest 请求结构
type MsgFromMsgServerRequest struct {
	MsgBody              string   `protobuf:"bytes,1,opt,name=MsgBody,proto3" json:"MsgBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgFromMsgServerRequest) Reset()         { *m = MsgFromMsgServerRequest{} }
func (m *MsgFromMsgServerRequest) String() string { return proto.CompactTextString(m) }
func (*MsgFromMsgServerRequest) ProtoMessage()    {}
func (*MsgFromMsgServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{0}
}
func (m *MsgFromMsgServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFromMsgServerRequest.Unmarshal(m, b)
}
func (m *MsgFromMsgServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFromMsgServerRequest.Marshal(b, m, deterministic)
}
func (m *MsgFromMsgServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFromMsgServerRequest.Merge(m, src)
}
func (m *MsgFromMsgServerRequest) XXX_Size() int {
	return xxx_messageInfo_MsgFromMsgServerRequest.Size(m)
}
func (m *MsgFromMsgServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFromMsgServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFromMsgServerRequest proto.InternalMessageInfo

func (m *MsgFromMsgServerRequest) GetMsgBody() string {
	if m != nil {
		return m.MsgBody
	}
	return ""
}

// MsgFromMsgServerReply 响应结构
type MsgFromMsgServerReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgFromMsgServerReply) Reset()         { *m = MsgFromMsgServerReply{} }
func (m *MsgFromMsgServerReply) String() string { return proto.CompactTextString(m) }
func (*MsgFromMsgServerReply) ProtoMessage()    {}
func (*MsgFromMsgServerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_afa6debe97205904, []int{1}
}
func (m *MsgFromMsgServerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgFromMsgServerReply.Unmarshal(m, b)
}
func (m *MsgFromMsgServerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgFromMsgServerReply.Marshal(b, m, deterministic)
}
func (m *MsgFromMsgServerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFromMsgServerReply.Merge(m, src)
}
func (m *MsgFromMsgServerReply) XXX_Size() int {
	return xxx_messageInfo_MsgFromMsgServerReply.Size(m)
}
func (m *MsgFromMsgServerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFromMsgServerReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFromMsgServerReply proto.InternalMessageInfo

func (m *MsgFromMsgServerReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgFromMsgServerRequest)(nil), "protomsg.MsgFromMsgServerRequest")
	proto.RegisterType((*MsgFromMsgServerReply)(nil), "protomsg.MsgFromMsgServerReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DbServerClient is the client API for DbServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DbServerClient interface {
	// 定义HandleMsgFromMsgServer方法
	HandleMsgFromMsgServer(ctx context.Context, in *MsgFromMsgServerRequest, opts ...grpc.CallOption) (*MsgFromMsgServerReply, error)
}

type dbServerClient struct {
	cc *grpc.ClientConn
}

func NewDbServerClient(cc *grpc.ClientConn) DbServerClient {
	return &dbServerClient{cc}
}

func (c *dbServerClient) HandleMsgFromMsgServer(ctx context.Context, in *MsgFromMsgServerRequest, opts ...grpc.CallOption) (*MsgFromMsgServerReply, error) {
	out := new(MsgFromMsgServerReply)
	err := c.cc.Invoke(ctx, "/protomsg.DbServer/HandleMsgFromMsgServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServerServer is the server API for DbServer service.
type DbServerServer interface {
	// 定义HandleMsgFromMsgServer方法
	HandleMsgFromMsgServer(context.Context, *MsgFromMsgServerRequest) (*MsgFromMsgServerReply, error)
}

func RegisterDbServerServer(s *grpc.Server, srv DbServerServer) {
	s.RegisterService(&_DbServer_serviceDesc, srv)
}

func _DbServer_HandleMsgFromMsgServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFromMsgServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServerServer).HandleMsgFromMsgServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protomsg.DbServer/HandleMsgFromMsgServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServerServer).HandleMsgFromMsgServer(ctx, req.(*MsgFromMsgServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DbServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protomsg.DbServer",
	HandlerType: (*DbServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleMsgFromMsgServer",
			Handler:    _DbServer_HandleMsgFromMsgServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcserver.proto",
}

func init() { proto.RegisterFile("grpcserver.proto", fileDescriptor_afa6debe97205904) }

var fileDescriptor_afa6debe97205904 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2f, 0x2a, 0x48,
	0x2e, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0xb9, 0xc5, 0xe9, 0x4a, 0xc6, 0x5c, 0xe2, 0xbe, 0xc5, 0xe9, 0x6e, 0x45, 0xf9, 0xb9, 0xbe, 0xc5,
	0xe9, 0xc1, 0x60, 0x35, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0xbe,
	0xc5, 0xe9, 0x4e, 0xf9, 0x29, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92,
	0x21, 0x97, 0x28, 0xa6, 0xa6, 0x82, 0x9c, 0x4a, 0x90, 0x96, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4,
	0x54, 0x98, 0x16, 0x28, 0xd7, 0x28, 0x8b, 0x8b, 0xc3, 0x25, 0x09, 0xa2, 0x54, 0x28, 0x8e, 0x4b,
	0xcc, 0x23, 0x31, 0x2f, 0x25, 0x27, 0x15, 0xdd, 0x10, 0x21, 0x45, 0x3d, 0x98, 0xc3, 0xf4, 0x70,
	0xb8, 0x4a, 0x4a, 0x1e, 0x9f, 0x92, 0x82, 0x9c, 0x4a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x0a, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xb8, 0x08, 0xdd, 0xf8, 0x00, 0x00, 0x00,
}
