/*******************************************************************************
*
*   COPYRIGHT   :   (c) 1995-1996 Sigma Designs, Inc. All rights reserved.
*
*   FILENAME    :   WinFMP.h
*
*   DESCRIPTION :   Main FMP header file.
*
*   PLATFORM    :   Windows
*
*   PROGRAMMER  :   ECY
*
*   COMMENTS    :   NONE
*
*   NOTES       :   Include this header file for FMP support.
*
*   CHANGES     :
*   08/10/95    -   Created.
*    (ECY)
*
*******************************************************************************/


#ifndef __WINFMP_H__
#define __WINFMP_H__


#include "FMPDefs.h"
#include "FMPMacs.h"
#include "FMPFctw.h"
#define MAKEDWORD(wLow, wHigh ) MAKELPARAM( wLow, wHigh )


#endif  /* __WINFMP_H__ */
